---
title: "R Notebook for Age & Hearing"
output: html_notebook
---

```{r}

library('dplyr')

source('setup.R')

tmp <- t3.data.15d %>% merge(t3.data.ssq,by = c('record_id','redcap_event_name')) %>%
  merge(t3.data.thi, c('record_id','redcap_event_name')) %>% 
  merge(df_fitting_rationale, c('record_id','redcap_event_name')) %>% merge(df_ioi, c('record_id','redcap_event_name'))

tmp <- tmp %>% merge(df_tinnitus, c('record_id')) %>%
merge(df_motivation, c('record_id')) %>%
merge(df_ha_use, c('record_id')) %>% 
merge(df_audiogram, c('record_id')) %>%
merge(df_CCI, c('record_id'))

```


```{r}

df_ssq.wider$ssq_speech_mean <- rowMeans(df_ssq.wider[,grepl("ssq_speech", colnames(df_ssq.wider))], na.rm = TRUE)
df_ssq.wider$ssq_space_mean <- rowMeans(df_ssq.wider[,grepl("ssq_space", colnames(df_ssq.wider))], na.rm = TRUE)
df_ssq.wider$ssq_sound_mean <- rowMeans(df_ssq.wider[,grepl("ssq_sound", colnames(df_ssq.wider))], na.rm = TRUE)

data.lr <- df_ssq.wider %>% merge(tmp, by = c('record_id') )

data.lr <- data.lr[,-c(134,45:63,123,115)]

data.lr.gn <- data.lr[data.lr$ha_manufactor.x == 'GN ReSound',]

data.lr.gn$ssq_mean <-  rowMeans(data.lr.gn[,c(21:23)], na.rm = TRUE)

data.lr.gn <- data.lr.gn[!is.na(data.lr.gn$own_ha.x),] 

```

Now let's add use_time_per_hour to dataframe and filter out those that use it less than 6 h per day

```{r}
data.UTH <- df_ha_use %>% select('record_id','ha_usetime_hours_per_day') %>% filter(ha_usetime_hours_per_day < 6) 
  
data.lr.gn.new <- data.lr.gn %>% filter(!(record_id %in% data.UTH$record_id))


```

Let's try to plot the SSQ benefit:

```{r}
library('ggplot2')
library('gridExtra')


p1 <- data.lr.gn.new %>% ggplot(aes(x = own_ha.x, y = ssq_speech_mean.x, fill = redcap_event_name)) + 
  geom_boxplot(width = 0.5) + scale_x_discrete(labels = c('New Users','Experienced')) + 
  labs(x = '',y = '',title = 'SSQ Speech') + scale_fill_discrete(name = 'Visit', labels = c('','')) +
  theme(axis.text = element_text(size = 20),
        legend.text = element_blank(),
        axis.title.y = element_text(size=20),
        legend.title = element_blank(),
        title = element_text(size = 23),
        legend.position = 'none') 
    
p2 <- data.lr.gn.new %>% ggplot(aes(x = own_ha.x, y = ssq_space_mean.x, fill = redcap_event_name)) + 
  geom_boxplot(width = 0.5) + scale_x_discrete(labels = c('New Users','Experienced')) + 
  labs(x = '',y = '',title = 'SSQ Space') + scale_fill_discrete(name = 'Visit', labels = c('','')) +
  theme(axis.text = element_text(size = 20),
        legend.text = element_blank(),
        axis.title.y = element_text(size=20),
        legend.title = element_blank(),
        title = element_text(size = 23),
        legend.position = 'none') 

p3 <- data.lr.gn.new %>% ggplot(aes(x = own_ha.x, y = ssq_sound_mean.x, fill = redcap_event_name)) + 
  geom_boxplot(width = 0.5) + scale_x_discrete(labels = c('New Users','Experienced')) + 
  labs(x = '',y = '',title = 'SSQ Sound') + scale_fill_discrete(name = 'Visit', labels = c('1st','2nd')) +
  theme(axis.text = element_text(size = 20),
        legend.text = element_text(size = 20),
        axis.title.y = element_text(size=20),
        legend.title = element_text(size=20),
        title = element_text(size = 23),
        legend.position = 'none')
  
p4 <- data.lr.gn.new %>% ggplot(aes(x = own_ha.x, y = ssq_mean, fill = redcap_event_name)) +   
  geom_boxplot(width = 0.5) + scale_x_discrete(labels = c('New Users','Experienced')) + 
  labs(x = '',y = '',title = 'Mean (Speech, Space, Sound)') + scale_fill_discrete(name = 'Visit', labels = c('1st','2nd')) +
  theme(axis.text = element_text(size = 20),
        legend.text = element_text(size = 20),
        axis.title.y = element_text(size=20),
        legend.title = element_text(size=20),
        title = element_text(size = 23))     

png('SSQ benefit.png',width = 1200, height = 900)

grid.arrange(p1,p2,p3,p4,ncol = 2, nrow = 2)

dev.off()

```
Now let's do an anova:

```{r}

library('dplyr')

attach(data.lr.gn.new)

summary(aov(ssq_speech_mean.x ~ redcap_event_name * own_ha.x))
summary(aov(ssq_space_mean.x ~ redcap_event_name * own_ha.x))
summary(aov(ssq_sound_mean.x ~ redcap_event_name * own_ha.x))
summary(aov(ssq_mean ~ redcap_event_name * own_ha.x))

detach(data.lr.gn.new)

```


Plot SSQ dependence on ha use time: 

```{r}
data.lr.gn.exp <- data.lr.gn.new[data.lr.gn$own_ha.x == 'Yes',]
data.lr.gn.new <- data.lr.gn.new[data.lr.gn$own_ha.x == 'No',]

#experienced
diff_speech<- data.lr.gn.exp$ssq_speech_mean.x[data.lr.gn.exp$redcap_event_name == 'besoeg2_arm_1'] - data.lr.gn.exp$ssq_speech_mean.x[data.lr.gn.exp$redcap_event_name == 'baseline_arm_1']

diff_space <- data.lr.gn.exp$ssq_space_mean.x[data.lr.gn.exp$redcap_event_name == 'besoeg2_arm_1'] - data.lr.gn.exp$ssq_space_mean.x[data.lr.gn.exp$redcap_event_name == 'baseline_arm_1']

diff_sound <- data.lr.gn.exp$ssq_sound_mean.x[data.lr.gn.exp$redcap_event_name == 'besoeg2_arm_1'] - data.lr.gn.exp$ssq_sound_mean.x[data.lr.gn.exp$redcap_event_name == 'baseline_arm_1']


time <- data.lr.gn.exp$ha_usetime_hours_per_day[data.lr.gn.exp$redcap_event_name == 'besoeg2_arm_1']

bla.exp <- data.frame(diff_speech,diff_space, diff_sound, time) 


p1 <- bla.exp %>% ggplot(aes(x = time, y = diff_speech)) +
  geom_point(size = 2, color = 'blue') + geom_smooth(color = 'red',size=2)  + scale_y_continuous(limits = c(-30,50)) +
  labs(x = 'Time [h]',y = 'SSQ benefit',title = 'Speech (Experienced Users)') +
  theme(axis.text = element_text(size = 18),
        legend.text = element_blank(),
        axis.title.y = element_text(size=18),
        legend.title = element_blank(),
        title = element_text(size = 20),
        legend.position = 'none') 

p2 <- bla.exp %>% ggplot(aes(x = time, y = diff_space)) +
  geom_point(size = 2, color = 'blue') + geom_smooth(color = 'red',size=2)  +scale_y_continuous(limits = c(-30,50)) +
  labs(x = 'Time [h]',y = '',title = 'Space (Experienced Users)') +
  theme(axis.text = element_text(size = 18),
        legend.text = element_blank(),
        axis.title.y = element_text(size=18),
        legend.title = element_blank(),
        title = element_text(size = 20),
        legend.position = 'none') 

p3 <- bla.exp %>% ggplot(aes(x = time, y = diff_sound)) +
  geom_point(size = 2, color = 'blue') + geom_smooth(color = 'red',size=2)   + scale_y_continuous(limits = c(-30,50))+
  labs(x = 'Time [h]',y = '',title = 'Sound (Experienced Users)')  +
  theme(axis.text = element_text(size = 18),
        legend.text = element_blank(),
        axis.title.y = element_text(size=18),
        legend.title = element_blank(),
        title = element_text(size = 20),
        legend.position = 'none') 


png('Time Exp User.png',width = 1500, height = 700)

grid.arrange(p1,p2,p3,ncol = 3)

dev.off()


#new

diff_speech<- data.lr.gn.new$ssq_speech_mean.x[data.lr.gn.new$redcap_event_name == 'besoeg2_arm_1'] - data.lr.gn.new$ssq_speech_mean.x[data.lr.gn.new$redcap_event_name == 'baseline_arm_1']

diff_space <- data.lr.gn.new$ssq_space_mean.x[data.lr.gn.new$redcap_event_name == 'besoeg2_arm_1'] - data.lr.gn.new$ssq_space_mean.x[data.lr.gn.new$redcap_event_name == 'baseline_arm_1']

diff_sound <- data.lr.gn.new$ssq_sound_mean.x[data.lr.gn.new$redcap_event_name == 'besoeg2_arm_1'] - data.lr.gn.new$ssq_sound_mean.x[data.lr.gn.new$redcap_event_name == 'baseline_arm_1']


time <- data.lr.gn.new$ha_usetime_hours_per_day[data.lr.gn.new$redcap_event_name == 'besoeg2_arm_1']

bla.new <- data.frame(diff_speech,diff_space, diff_sound, time) 


p1 <- bla.new %>% ggplot(aes(x = time, y = diff_speech)) +
  geom_point(size = 2, color = 'blue') + geom_smooth(color = 'red',size=2)  + scale_y_continuous(limits = c(-30,50)) +
  labs(x = 'Time [h]',y = 'SSQ benefit',title = 'Speech (New Users)') +
  theme(axis.text = element_text(size = 18),
        legend.text = element_blank(),
        axis.title.y = element_text(size=18),
        legend.title = element_blank(),
        title = element_text(size = 20),
        legend.position = 'none') 

p2 <- bla.new %>% ggplot(aes(x = time, y = diff_space)) +
  geom_point(size = 2, color = 'blue') + geom_smooth(color = 'red',size=2)  +scale_y_continuous(limits = c(-30,50)) +
  labs(x = 'Time [h]',y = '',title = 'Space (New Users)') +
  theme(axis.text = element_text(size = 18),
        legend.text = element_blank(),
        axis.title.y = element_text(size=18),
        legend.title = element_blank(),
        title = element_text(size = 20),
        legend.position = 'none') 

p3 <- bla.new %>% ggplot(aes(x = time, y = diff_sound)) +
  geom_point(size = 2, color = 'blue') + geom_smooth(color = 'red',size=2)   + scale_y_continuous(limits = c(-30,50))+
  labs(x = 'Time [h]',y = '',title = 'Sound (New Users)')  +
  theme(axis.text = element_text(size = 18),
        legend.text = element_blank(),
        axis.title.y = element_text(size=18),
        legend.title = element_blank(),
        title = element_text(size = 20),
        legend.position = 'none') 

png('Time New User.png',width = 1500, height = 700)

grid.arrange(p1,p2,p3,ncol = 3)

dev.off()

```

