---
title: "Models in the report"
output: html_notebook
---
```{r}

# Labels
ioi_label_4 <- c('Not at all', 'Slightly', 'Moderately', 'Considerably', 'Significantly')
ioi_label_7 <- c('For the worse', 'No change', 'Slightly','Considerably', 'Significantly', 'No answer')

d_label <- c('Move', 'Sight', 'Hear', 'Breathe', 'Sleep', 'Eat', 'Speak', 'Pee', 'Activity', 'Mental', 'Unpleasant', 'Depression', 'Stress', 'Power', 'Sex')

# New colors based on RColorBrewer "RdYlBu"
brewer.pal(11,"RdYlBu")
col2 <-c("#FDAE61",  "#74ADD1")
col3_red <-c("#F46D43", "#FDAE61", "#74ADD1")
col3_blue <- c("#FDAE61", "#74ADD1", "#4575B4")
col5 <- c("#D73027","#F46D43","#FEE090","#74ADD1","#4575B4")
```


# [2.3] The Current Process of Hearing Aid Fitting 
```{r}
ggplot(melted_grouped_audiogram, aes(x=variable, y=value, group=Class, color=Class)) +
  geom_point(stat='summary', fun.y=mean) +
  stat_summary(fun.y=mean, geom="line") + scale_y_reverse() + 
  xlab("Frequecy (hz)") + ylab("Sound Threshold  (dB)") + theme_minimal()
```

# [2.4] Mahina Learnia
```{r}
d <- women
d$predicted <- predict(lm(height ~ weight, women))
d$x <- d$weight
d$y <- d$height
formula <- y ~ x
ggplot(d, aes(x=weight, y=height)) +
    geom_point(color = col2[1]) +
    geom_smooth(color = col2[2], method = "lm", formula = formula) +
    geom_segment(aes(xend = weight, yend = predicted), color = col2[1]) +
    theme_minimal()

formula <- y ~ x
ggplot(d, aes(weight, height)) +
  geom_point(color = col2[1]) +
  geom_segment(aes(xend = weight, yend = predicted), color = col2[1]) +
  geom_smooth(color = col2[2], method = "lm", formula = formula) +
  stat_fit_glance(method = "lm", 
                  method.args = list(formula = formula),
                  label.x = "right",
                  label.y = "bottom",
                  aes(label = paste("italic(P)*\"-value = \"*", 
                                    signif(..p.value.., digits = 4), sep = "")),
                  parse = TRUE) +
    theme_minimal()
```


```{r}
set.seed(1024)

randomdata <- data.frame(X = runif(5, -20, 20) + rnorm(500, 0, 4), Y = runif(5, -20, 20) + rnorm(500, 0, 4))
randomdata$cluster <- factor(kmeans(randomdata, 5)$cluster)
ggplot(randomdata, aes(x = X, y = Y, color = cluster)) +
    geom_point() + scale_color_brewer(palette = "RdYlBu") + theme_minimal()
randomdata$cluster <- factor(kmeans(randomdata, 5)$cluster)
ggplot(randomdata, aes(x = X, y = Y, color = cluster)) +
    geom_point() + scale_color_brewer(palette = "RdYlBu") + theme_minimal()
randomdata$cluster <- factor(kmeans(randomdata, 5)$cluster)
ggplot(randomdata, aes(x = X, y = Y, color = cluster)) +
    geom_point() + scale_color_brewer(palette = "RdYlBu") + theme_minimal()



```


# [4.1.1] Information tables
```{r, fig.width=12}

dat <- filter(df_motivation, !is.na(own_ha))
dat <- df_motivation
dat2 <- dat %>% group_by(sex)

grid.arrange(
  ggplot(dat) + 
    geom_area(aes(x=age, y=..count../max(..count..)), stat = "count", fill=colors[1]) +
    geom_line(aes(x=age, y=cumsum(..count..)/sum(..count..)), stat="count", color=colors[2], size=1) +
    ylab("") + scale_y_continuous(labels = percent) + ggtitle("Age distribution") + xlab("Age") + theme_minimal(),
  
  ggplot(data = dat, aes(x=sex,fill=sex)) + 
    geom_bar() + theme_minimal() + scale_fill_manual(values = colors) + theme(legend.position="none"),
  
  ggplot(filter(dat, !is.na(own_ha))) + 
    geom_bar(aes(x=factor(1), fill=own_ha), position = "fill") + scale_y_continuous(labels = percent) + coord_polar(theta = "y") +
    ggtitle("Owns Hearing Aid") + xlab("") + ylab("") + theme_minimal()+ scale_fill_manual(values = colors),
  
  ggplot(dat) + 
    geom_boxplot(aes(y=age, x=sex, fill=sex)) +
    ylab("Age") + xlab("") +
    ggtitle("Age/Sex") + theme_minimal()+theme(legend.position="none")+ scale_fill_manual(values = colors),
  
  ggplot(filter(dat, !is.na(own_ha))) + 
    geom_boxplot(aes(y=age, fill=own_ha, x=own_ha)) +
    ylab("Age") + xlab("") +
    ggtitle("Age/Owns Hearing Aid") + theme_minimal()+theme(legend.position="none")+ scale_fill_manual(values = colors),
  
  ggplot(filter(dat, !is.na(own_ha))) + 
    geom_bar(aes(fill=own_ha, x=sex), position = "fill") +
    ggtitle("Sex/Owns Hearing Aid") + theme_minimal()+ scale_fill_manual(values = colors),
  ncol=3
)
```

```{r}
df_own.ha <- df_motivation %>% filter(own_ha == "Yes")
df_own.ha.no <- df_motivation %>% filter(own_ha == "No")

df_own.ha.ssq <- merge(df_own.ha, t3.data.ssq.follow, by=c("record_id"))

df_own.ha.ssq <- merge(df_own.ha, df_ioi %>% filter(redcap_event_name == "baseline_arm_1"), by="record_id")
df_own.ha.no <- merge(df_own.ha.no, df_ioi %>% filter(redcap_event_name == "besoeg2_arm_1"), by="record_id")

temp <- merge(df_own.ha, df_ioi %>% filter(redcap_event_name == "besoeg2_arm_1"), by="record_id")

df_own.ha.ssq
df_own.ha.no

grid.arrange(
  ggplot(df_own.ha.ssq %>% filter(!is.na(ioi_ha_4)), aes(x = ioi_ha_4)) + 
    geom_bar(fill=col2[1]) + 
    ggtitle(label = "Has your current HA been worth the trouble?", subtitle = "(Baseline/owns HA)") +
    theme_minimal() + 
    scale_x_discrete(labels=ioi_label_4) + 
    xlab(label = "") + ylab(label = "Count") + coord_flip()+ 
    geom_text(stat="count", aes(label = percent(..count../sum(..count..))), hjust="right"),

  ggplot(df_own.ha.no %>% filter(!is.na(ioi_ha_4)), aes(x= ioi_ha_4)) +
    geom_bar(fill=col2[1]) + 
    ggtitle(label = "",subtitle = "(Follow-up)") +
    theme_minimal() + xlab(label = "") + 
    scale_x_discrete(labels=ioi_label_4) +
    ylab(label = "Count") + coord_flip() +
    geom_text(stat="count", aes(label = percent(..count../sum(..count..))), hjust="right"),
    
  ncol=1
)


ggplot(temp %>% filter(!is.na(ioi_ha_4)), aes(x= ioi_ha_4)) + geom_bar(fill=col2[1]) + 
  ggtitle(label = "",subtitle = "(Follow-up/owns HA)") +
  theme_minimal() + xlab(label = "") + 
  scale_x_discrete(labels=ioi_label_4) +
  ylab(label = "Count") + coord_flip() + 
  geom_text(stat="count", aes(label = percent(..count../sum(..count..))))
```


#[4.1.2] Audiometric data
```{r}
ggplot(melted_grouped_audiogram, aes(x=variable, y=value, group=Class, color=Class)) +
    geom_point(stat='summary', fun.y=mean) +
    stat_summary(fun.y=mean, geom="line") + scale_y_reverse() + 
    xlab("Frequecy (hz)") + ylab("Sound Threshold  (dB)") + theme_minimal()

ggplot(df_user_worstear,aes(x=class)) + geom_bar(fill=col2[1], color="orange") +
  geom_text(stat='count', aes(label=..count..), vjust=-1) + ylim(0,700) + theme_minimal()


```


# [4.2] Defining Drawer Users 

```{r,fig.height=5}
#ggplot(df_ha_use) + geom_boxplot(aes(y=ha_usetime_hours_per_day, x=sex, fill=sex))


t3.data.ssq.follow <- filter(t3.data.ssq, redcap_event_name == "besoeg2_arm_1")

t3.data.ssq.follow <- merge(t3.data.ssq.follow, df_user_worstear, by="record_id")

t3.data.ssq.follow <- merge(t3.data.ssq.follow, df_ha_use, by="record_id")


grid.arrange(

  ggplot(df_ha_use, aes(x=ha_usetime_hours_per_day)) + 
    geom_histogram(color="orange",fill=col2[1],bins = 24) +
    geom_text(stat='bin',aes(label=..count.., vjust="top"), color="#122312", bins=24, size=3) +
    theme_minimal() + ggtitle("Distribution of participants (use time)") + xlab("Hours of use per day") + ylab("Count"),
  
    ggplot(t3.data.ssq.follow, aes(x=" ", fill=IsT1DrawerUser)) + 
    geom_bar() + geom_text(stat='count',aes(label=..count.., y=..count../2), color="#122312", bins=24) +
    theme_minimal() + ggtitle("Amount of drawer users") + xlab("") + ylab("Count") + scale_fill_manual("Drawer user (<3h/day)", values = col2) + coord_flip(),
  ncol=1

)

ggplot(t3.data.ssq.follow, aes(x=" ", fill=IsDrawerUser)) + 
  geom_bar(position = "dodge") +
  theme_minimal()

```

```{r}
grid.arrange(
  ggplot(t3.data.ssq.follow) + geom_boxplot(aes(x=class, y=ha_usetime_hours_per_day))+
  theme_minimal() + ggtitle("Average use time per hearing loss clasification") + xlab("Hearing loss classification") + ylab("Hours of use per day"),
  
  ggplot(t3.data.ssq.follow) + geom_bar(aes(x=class, fill=IsDrawerUser), position = "fill") +
  theme_minimal() + ggtitle("Distribution of drawer users in hearing loss clasification") + xlab("Hearing loss classification") + ylab("Count (%)") + scale_fill_manual("Drawer user?", values = col3_blue),
  ncol=1
)
```

# [4.3] use -> satisfaction
```{r}
requireLibrary('rpart')
requireLibrary('partykit')
requireLibrary('rpart.plot')
requireLibrary('randomForest')

# ioi ha 7
ggplot(df_ioi_follow, aes(x = ioi_ha_7)) + geom_bar(fill=col2[1], color="orange") + 
  ggtitle("How much has your current HA increased your life satisfaction?") + 
  geom_text(stat='count', aes(label=..count..), vjust=-1) + ylim(0,700) + theme_minimal() + 
  scale_x_discrete(labels=ioi_label_7) + xlab("")

ggplot(merge(df_ioi, df_ha_use %>% select(record_id, ha_usetime_hours_per_day), by="record_id"), aes(x=ioi_ha_7, ha_usetime_hours_per_day)) + geom_boxplot() + 
  theme_minimal() + scale_x_discrete(labels=ioi_label_7) + xlab("Life satisfaction change") +
  ylab("Use-time (Hours/day)")


```

Tree

```{r, fig.width=12}
eq_ioi_2 <- ioi_ha_7 ~ ioi_ha_1 + ioi_ha_2 + ioi_ha_3 + ioi_ha_4 + ioi_ha_5 + ioi_ha_6  
fit3.forest <- randomForest(eq_ioi_2,data = na.omit(ioi_use))
fit4.rpart <- rpart(eq_ioi_2, data = ioi_use_follow.ssq, method = "class", parms = list(split = "information"))

randomForest::importance(fit3.forest)
varImpPlot(fit3.forest)

rpart.plot(fit4.rpart, box.palette = 'RdBu', type = 3, branch.lty = 3)

ioi_use <- ioi_use %>% filter(ha_usetime_hours_per_day <= 16)

ioi_use_clust <- merge(ioi_use, t3.data.ssq.diff, by=c('record_id'))
levels(ioi_use_clust$Cluster) <- c("Low benefit", "Moderate Benefit","High Benefit")

ggplot(ioi_use_clust, aes(y=as.numeric(ioi_ha_7),x = ha_usetime_hours_per_day,color=Cluster)) + 
  geom_smooth(method = lm, size=1, fill="transparent") + 
  xlab("Use time (hours/day)") + ylab("Life satisfaction") + theme_minimal() + theme(text = element_text(size = 20)) +
  ggtitle("Use-time & life satisfaction") + ylim(1,5) + scale_color_manual(values = col3_red) + scale_fill_manual(values=col3_red) + pvalue

s <- lm(as.numeric(ioi_ha_7) ~ ha_usetime_hours_per_day, data=ioi_use_clust %>% filter(Cluster=="Low benefit"))
summary(s)


s <- lm(as.numeric(ioi_ha_7) ~ ha_usetime_hours_per_day, data=ioi_use_clust %>% filter(Cluster=="Moderate Benefit"))
summary(s)


s <- lm(as.numeric(ioi_ha_7) ~ ha_usetime_hours_per_day, data=ioi_use_clust %>% filter(Cluster=="High Benefit"))
summary(s)

```

# [4.5] Perceived hearing loss and benefit
```{r, fig.width=6,fig.height=5}

#Benefit
grid.arrange(
  # SSQ - baseline
  ggplot(data=melted.temp ,aes(variable, value)) + 
    geom_line(aes(color = Cluster, group = Cluster), size=1) +
    scale_color_manual("Benefit",values= col3_red, labels=c("Low","Medium","High")) + 
    ggtitle("Baseline SSQ score") + 
    xlab("Question (speech, space, sound)") + ylab("Score") + theme_minimal() + ylim(0, 100)+theme(legend.position = "none"),
  
  # SSQ - Diff
  ggplot(data=melted_clus.res ,aes(variable, value)) + 
    geom_line(aes(color = Cluster, group = Cluster), size=1) +
    scale_color_manual("Benefit",values= col3_red, labels=c("Low","Medium","High")) + 
    ggtitle("Difference of SSQ score from baseline to follow-up") + 
    xlab("Question (speech, space, sound)") + ylab("Difference") + theme_minimal(),
  
  # SSQ- Follow
  ggplot(data=melted_follow ,aes(variable, value)) + 
    geom_line(aes(color = Cluster, group = Cluster), size=1) +
    scale_color_manual("Benefit",values= col3_red, labels=c("Low","Medium","High")) + 
    ggtitle("Follow-up SSQ score") + 
    xlab("Question (speech, space, sound)") + ylab("Score") + theme_minimal() + ylim(0, 100)+theme(legend.position = "none"),
  
  # Audigram in clusters
  ggplot(t3.data.ssq.diff) + 
    geom_bar(aes(x=Cluster, fill=class), position='fill', color="black") + 
    scale_fill_brewer("Hearing Loss\nClassification",palette = "RdYlBu", direction = -1) + 
    ggtitle("Distribution of classifications") + ylab("Count (%)") +xlab("Benefit")+ theme_minimal() +scale_x_discrete(labels=c("Low","Medium","High")),
  
  nrow=2,ncol=2
)


```
```{r, fig.width=10,fig.height=3}

grid.arrange(
    # SSQ - baseline
  ggplot(data=melted.temp ,aes(variable, value)) + 
    geom_line(aes(color = Cluster, group = Cluster), size=1) +
    scale_color_manual("Benefit",values= col3_red, labels=c("Low","Medium","High")) + 
    ggtitle("Baseline SSQ score") + 
    xlab("Question (speech, space, sound)") + ylab("Score") + theme_minimal() + ylim(0, 100)+theme(legend.position = "none"),
    # SSQ- Follow
  ggplot(data=melted_follow ,aes(variable, value)) + 
    geom_line(aes(color = Cluster, group = Cluster), size=1) +
    scale_color_manual("Benefit",values= col3_red, labels=c("Low","Medium","High")) + 
    ggtitle("Follow-up SSQ score") + 
    xlab("Question (speech, space, sound)") + ylab("Score") + theme_minimal() + ylim(0, 100),
  nrow=1
)
```


```{r, fig.width=9,fig.height=3}
# Use-time & Drawer users
grid.arrange(

  ggplot(t3.data.ssq.diff) + geom_bar(aes(x=Cluster, fill=Cluster), color="black")+ scale_fill_manual(values=col3_red) + 
    theme_minimal()+ theme(legend.position = "none") + ggtitle("Size of clusters") + ylab("Count") + xlab("Benefit")+scale_x_discrete(labels=c("Low","Medium","High")),
  
  ggplot(t3.data.ssq.diff,aes(x=Cluster, fill=factor(IsT1DrawerUser, labels=c("No","Yes")), color=Cluster)) + geom_bar(position="fill", color="black") +
      scale_fill_manual(values=col3_red)+ theme_minimal() + theme(legend.position = "none") + ylab("Count (%)") + scale_y_continuous(labels = percent, limits = c(0,0.2)) +
      ggtitle("Percentage of drawer users")+xlab("Benefit")+scale_x_discrete(labels=c("Low","Medium","High")),
  
  ggplot(t3.data.ssq.diff %>% 
           merge(select(df_ha_use, record_id, ha_usetime_hours_per_day), by="record_id") %>% filter(ha_usetime_hours_per_day < 18)) + 
    geom_boxplot(aes(x=Cluster, fill=Cluster, y=ha_usetime_hours_per_day), color="black")+
    scale_fill_manual("", values=col3_red)+ 
    ylab("Use time in hours per day")+ theme(legend.position = "empty") + 
    ggtitle("Average use time") +xlab("Benefit")+ theme_minimal() +scale_x_discrete(labels=c("Low","Medium","High"))+theme(legend.position = "none"),

  nrow=1
)
```


```{r, fig.width=10}
melted_15d <- melt(df_15d[,c(1:3,5,7,11:16)], id.vars = c('record_id', 'redcap_event_name'))

grid.arrange(
  ggplot(melted_15d %>% filter(redcap_event_name == 'baseline_arm_1') %>% na.omit) + 
  #geom_boxplot(aes(x=variable, y=value)) + coord_flip()
  geom_bar(aes(x=variable, fill=value),position = 'fill' ,color="black") + scale_x_discrete(labels = d_label_2) + ylab("") + xlab("") + 
  scale_fill_brewer("Score",palette = "RdYlBu", direction = -1, labels= c("Best","","","","Worst")) + theme_minimal() + ggtitle("Baseline"),

ggplot(melted_15d %>% filter(redcap_event_name == 'besoeg2_arm_1') %>% na.omit) + 
  #geom_boxplot(aes(x=variable, y=value)) + coord_flip()
  geom_bar(aes(x=variable, fill=value),position = 'fill' ,color="black")  + scale_x_discrete(labels=d_label_2) + ylab("") + xlab("") + 
  scale_fill_brewer("Score",palette = "RdYlBu", direction = -1, labels= c("Best","","","","Worst")) + theme_minimal() + ggtitle("Follow-up"), 

ncol=1
)
d_label_2 <- c('Move', 'Hear', 'Sleep', 'Activity', 'Mental', 'Unpleasant', 'Depression', 'Stress', 'Power')
```

# [4.4.1] complex > rest
resten kan findes i dok. ssq-complex-use

```{r}

ggplot(ssq_use_fil, aes(y=ha_usetime_hours_per_day)) + 
  geom_smooth(method='loess', aes(x=ssq_speech_mean, color="Speech")) +
  geom_smooth(method='loess', aes(x=ssq_space_mean, color="Space")) + 
  geom_smooth(method='loess', aes(x=ssq_sound_mean, color="Sound")) + 
  xlab("Difference from baseline to followup") + ylab("Use time (hours/day)") + theme_light()  + scale_colour_manual("", 
                      breaks = c("Speech", "Space", "Sound"),
                      values = c("Speech"="green", "Space"="red", 
                                 "Sound"="blue"))
ssq_use_fil <- ssq_use %>% filter(ha_usetime_hours_per_day < 16)

ssq_useless <- ssq_use %>% filter(ha_usetime_hours_per_day >= 16)

summary(ssq_useless)

ggplot(ssq_use_fil, aes(y=ha_usetime_hours_per_day)) + 
  geom_smooth(method=lm, aes(x=ssq_speech_mean, color="Speech")) +
  geom_smooth(method=lm, aes(x=ssq_space_mean, color="Space")) + 
  geom_smooth(method=lm, aes(x=ssq_sound_mean, color="Sound")) + 
  xlab("Difference from baseline to followup") + ylab("Use time (hours/day)") + theme_light()  + scale_colour_manual("", 
                      breaks = c("Speech", "Space", "Sound"),
                      values = c("Speech"="green", "Space"="red", 
                                 "Sound"="blue"))# +

melted_ssq_use <- melt(ssq_use_fil[,c(3:14, 24)], id.vars = 'ha_usetime_hours_per_day')


ggplot(melted_ssq_use, aes(x=value, y=ha_usetime_hours_per_day)) + 
  geom_smooth(aes(color=variable), se=F) + 
  theme_light()


ggplot(melted_ssq_use, aes(x=value, y=ha_usetime_hours_per_day)) + 
  geom_smooth(aes(color=variable), se=F, method = lm) + 
  theme_light() + ylab("Hours/day") + xlab("Difference from baseline to followup")


s <- lm(ha_usetime_hours_per_day ~ ssq_sound_mean, data=ssq_use_fil)
summary(s)
s <- lm(ha_usetime_hours_per_day ~ ssq_speech_mean, data=ssq_use_fil)
summary(s)
s <- lm(ha_usetime_hours_per_day ~ ssq_space_mean, data=ssq_use_fil)
summary(s)

geom_bin2d(bins=2,aes(x=ssq_sound_mean))
  

mboy <- melt(ssq_use_fil[c(16:18, 24)], id.vars = "ha_usetime_hours_per_day")

p <- ggplot(mboy,aes(x=value, y=ha_usetime_hours_per_day))+geom_bin2d(bins=20) + theme_light() + ylab("Hours/day")

p <- p + facet_wrap( ~ variable, ncol=3)

ggplotly(p)

```

# [4.7] Finish him
```{r}
pvalue <-  stat_fit_glance(method = "lm", 
                  method.args = list(formula = y ~ x),
                  label.x = "right",
                  label.y = "bottom",
                  aes(label = paste("italic(P)*\"-value = \"*", 
                                    signif(..p.value.., digits = 4), sep = "")),
                  parse = TRUE)

data_4_7 <- t3.diff.ssq.no.na %>% select(record_id, starts_with("ssq_")) %>% 
  merge(df_ioi.no.na %>% select(record_id, starts_with("ioi_ha_")), by="record_id")

formula <- y ~ x
ggplot(data_4_7 %>% select(ioi_ha_2, ends_with("mean")) %>% melt, aes(x=value, y=as.numeric(ioi_ha_2), color=variable)) +
  geom_smooth(method = "lm", formula = formula, se=F) + pvalue + scale_y_continuous(breaks = 1:5, labels=c("worse","same","little better", "better", "much better"), limits = c(1,5)) + 
  theme_light() + ylab("Specific scenario improvement") +  xlab("SSQ difference (baseline X followup)")+
  scale_color_manual(values=col3_red)


ggplot(data_4_7 %>% select(ioi_ha_2, starts_with("ssq_speech"),-ends_with("mean")) %>% melt, aes(x=value, y=as.numeric(ioi_ha_2), color=variable)) +
  geom_smooth(method = "lm", formula = formula, se=F) + pvalue + scale_y_continuous(breaks = 1:5, labels=c("worse","same","little better", "better", "much better"), limits = c(1,5)) + 
  theme_light() + ylab("Specific scenario improvement") +  xlab("SSQ difference (baseline X followup)")+
  scale_color_brewer(palette = "Dark2")

ggplot(data_4_7 %>% select(ioi_ha_7, ends_with("mean")) %>% melt, aes(x=value, y=as.numeric(ioi_ha_7), color=variable)) +
  geom_smooth(method = "lm", formula = formula, se=F) + pvalue + scale_y_continuous(breaks = 1:5, labels=c("worse","same","little better", "better", "much better"), limits = c(1,5)) + 
  theme_light() + ylab("Life satisfaction improvement") + xlab("SSQ difference (baseline X followup)")+
  scale_color_manual(values=col3_red)
```


```{r}
lm(ioi_ha_2~., data_4_7 %>% select(ioi_ha_2, starts_with("ssq_"),-ends_with("mean")))
lm(ioi_ha_7~., data_4_7 %>% select(ioi_ha_7, starts_with("ssq_"),-ends_with("mean")))

lms <- c()
for (q in 2:13) {
  lms <- c(lms, lm(ioi_ha_2~., data_4_7[,c(q,18)]))
}

for(m in lms){
  print(m)
}

lms <- c()
for (q in 2:13) {
  lms <- c(lms, lm(ioi_ha_7~., data_4_7[,c(q,23)]))
}
lms[1]$coefficients

lm(ioi_ha_2~., data_4_7[,c(2,18)])
lm(ioi_ha_2~., data_4_7[,c(3,18)])
lm(ioi_ha_2~., data_4_7[,c(4,18)])
lm(ioi_ha_2~., data_4_7[,c(5,18)])
lm(ioi_ha_2~., data_4_7[,c(6,18)])
lm(ioi_ha_2~., data_4_7[,c(7,18)])
lm(ioi_ha_2~., data_4_7[,c(8,18)])
lm(ioi_ha_2~., data_4_7[,c(9,18)])
lm(ioi_ha_2~., data_4_7[,c(10,18)])
lm(ioi_ha_2~., data_4_7[,c(11,18)])
lm(ioi_ha_2~., data_4_7[,c(12,18)])
lm(ioi_ha_2~., data_4_7[,c(13,18)])
```


