---
title: "R Notebook"
output: html_notebook
---

Trying to make a tree with everything

```{r}

ssq_diff <- t3.diff.ssq.no.na %>% select(record_id,redcap_event_name,starts_with("ssq_"))
colnames(ssq_diff) <- c(colnames(ssq_diff[,1:2]), paste0(colnames(ssq_diff[,3:17]), "_diff"))
df_everything <- t3.data.15d.no.na %>% select(record_id, redcap_event_name, starts_with("fifteen_d_")) %>% 
  merge(
    t3.data.ssq.no.na %>% select(record_id,redcap_event_name,starts_with("ssq_"), IsT1DrawerUser)
    , by=c("record_id", "redcap_event_name")) %>% merge(
      t3.data.thi.no.na %>% select(record_id,redcap_event_name, tinnitus, starts_with("tinnitus_"),-ends_with("complete"))
    , by=c("record_id", "redcap_event_name")) %>% merge(
      df_ioi.no.na %>% select(record_id, starts_with("ioi_ha_"))
    , by=c("record_id")) %>% merge(
      ssq_diff %>% select(record_id, starts_with("ssq_"))
    , by=c("record_id")) %>% merge(
      df_ha_use.no.na %>% select(record_id, own_ha, ha_number_of_ha, ha_use_time, ha_usetime_hours_per_day, sex, age)
    , by=c("record_id")) %>%  merge(
      df_audiogram %>% select(record_id, Class)
    , by=c("record_id"))

summary(df_everything)
  
```


```{r, fig.width=20}
drops <- c('redcap_event_name','record_id','ioi_ha_1')
data.lr <- df_everything[,!(names(df_everything) %in% drops)]
data.lr$IsT1DrawerUser <- factor(data.lr$IsT1DrawerUser,labels = c('Not in Drawer','In Drawer'))

fit.rpart <- rpart(IsT1DrawerUser~.-ha_usetime_hours_per_day, data = data.lr, method = 'class', parms = list(split = 'information'), control = rpart.control(cp = 0.0077, maxdepth = 5))

rpart.plot(fit.rpart, type = 5, yesno = 2, extra = 106)



fit.rpart <- rpart(ha_usetime_hours_per_day~., data = data.lr[,c(1:30,32:85)], method = 'anova', parms = list(split = 'gini'), control = rpart.control(cp = 0.0077, maxdepth = 5))

rpart.plot(fit.rpart, type = 5, yesno = 2, extra = 101)
```

## PCA Tree
```{r, fig.width=12}
d1 <- df_everything %>% 
  select(everything(), -starts_with("tinnitus"), -ioi_ha_1, -redcap_event_name, -record_id, -ha_usetime_hours_per_day, -IsT1DrawerUser) %>%
  mutate_if(is.factor, as.numeric)
pca.fit <- prcomp(d1, scale. = T)

ssq.cor <- cor(d1, use = 'complete.obs')
nr.factors <- fa.parallel(ssq.cor, fa = 'fa', n.obs = 1700)

fa.ssq <- fa(ssq.cor, nfactors = 7, rotate = 'varimax', fm = 'pa',SMC = FALSE, n.obs = 6844)

#pca.fit
fviz_eig(pca.fit)

d2 <- data.frame(pca.fit$rotation)
d2$col <- rownames(d2)

ggplot(d2[,c(paste0("PC",1:5),"col")] %>% melt(id.vars="col"), aes(x=col, y=value)) + geom_col()+ facet_wrap(~variable)+theme(axis.text.x = element_text(angle=90))
```

#So confused?
```{r, fig.asp=0.5, fig.width=12}
load <- data.frame(pca.fit$rotation)[,1:6]
load$name <- rownames(load)
data <- load %>% melt(id.vars="name") %>% mutate_if(is.numeric, function(x)ifelse(abs(x)<0.15, 0, x))
ggplot(data ) + geom_col(aes(y=value, fill=variable, x=name), color=rgb(0,0,0,0.5))+ theme_light() + theme(axis.text.x = element_text(angle=90, vjust = 0.5)) + labs(fill="Component", x="Variable", y="Loading") + ggtitle("Loadings of Principal Component Analysis") + scale_fill_brewer(palette = "RdYlBu")
```


```{r}
d3 <- data.frame(pca.fit$x[,1:5])
names(d3) <- c("SSQ?","High SSQ, low Diff","Fifteen D","-ioi+years+own_ha+class","-ioi-activity-numberOfHa")
d3$ha_hours <- df_everything$ha_usetime_hours_per_day
fit.rpart <- rpart(ha_hours~., data = d3, method = 'anova', parms = list(split = 'gini'), control = rpart.control(cp = 0.0077, maxdepth = 5))

rpart.plot(fit.rpart, type = 5, yesno = 2, extra = 1)


d3 <- data.frame(pca.fit$x[,1:5])
names(d3) <- c("SSQ?","High SSQ, low Diff","Fifteen D","-ioi+years+own_ha+class","-ioi-activity-numberOfHa")
d3$IsDrawer <- df_everything$IsT1DrawerUser
fit.rpart <- rpart(IsDrawer~., data = d3, method = 'class', parms = list(split = 'information'), control = rpart.control(cp = 0.0007, maxdepth = 5))

rpart.plot(fit.rpart, type = 5, yesno = 2, extra = 106)
```

